# Generated by Django 6.0.1 on 2026-04-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(max_length=10, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(max_length=150, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='food_type',
            field=models.CharField(choices=[('AI', 'Всё включено'), ('OB', 'Только завтраки'), ('BD', 'Завтрак и ужин'), ('NO', 'Нет питания')], max_length=2, verbose_name='Тип питания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.CharField(max_length=200, verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за человека'),
        ),
    ]
